using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Normal.Realtime;
using Normal.Realtime.Serialization;

[RealtimeModel]
public partial class RealtimeNormcoreTourTeleportController
{
    [RealtimeProperty(1, true, true)]
    private bool _isTeleportEnabled;
}

/* ----- Begin Normal Autogenerated Code ----- */
public partial class RealtimeNormcoreTourTeleportController : RealtimeModel {
    public bool isTeleportEnabled {
        get {
            return _cache.LookForValueInCache(_isTeleportEnabled, entry => entry.isTeleportEnabledSet, entry => entry.isTeleportEnabled);
        }
        set {
            if (this.isTeleportEnabled == value) return;
            _cache.UpdateLocalCache(entry => { entry.isTeleportEnabledSet = true; entry.isTeleportEnabled = value; return entry; });
            InvalidateReliableLength();
            FireIsTeleportEnabledDidChange(value);
        }
    }
    
    public delegate void PropertyChangedHandler<in T>(RealtimeNormcoreTourTeleportController model, T value);
    public event PropertyChangedHandler<bool> isTeleportEnabledDidChange;
    
    private struct LocalCacheEntry {
        public bool isTeleportEnabledSet;
        public bool isTeleportEnabled;
    }
    
    private LocalChangeCache<LocalCacheEntry> _cache = new LocalChangeCache<LocalCacheEntry>();
    
    public enum PropertyID : uint {
        IsTeleportEnabled = 1,
    }
    
    public RealtimeNormcoreTourTeleportController() : this(null) {
    }
    
    public RealtimeNormcoreTourTeleportController(RealtimeModel parent) : base(null, parent) {
    }
    
    protected override void OnParentReplaced(RealtimeModel previousParent, RealtimeModel currentParent) {
        UnsubscribeClearCacheCallback();
    }
    
    private void FireIsTeleportEnabledDidChange(bool value) {
        try {
            isTeleportEnabledDidChange?.Invoke(this, value);
        } catch (System.Exception exception) {
            UnityEngine.Debug.LogException(exception);
        }
    }
    
    protected override int WriteLength(StreamContext context) {
        int length = 0;
        if (context.fullModel) {
            FlattenCache();
            length += WriteStream.WriteVarint32Length((uint)PropertyID.IsTeleportEnabled, _isTeleportEnabled ? 1u : 0u);
        } else if (context.reliableChannel) {
            LocalCacheEntry entry = _cache.localCache;
            if (entry.isTeleportEnabledSet) {
                length += WriteStream.WriteVarint32Length((uint)PropertyID.IsTeleportEnabled, entry.isTeleportEnabled ? 1u : 0u);
            }
        }
        return length;
    }
    
    protected override void Write(WriteStream stream, StreamContext context) {
        var didWriteProperties = false;
        
        if (context.fullModel) {
            stream.WriteVarint32((uint)PropertyID.IsTeleportEnabled, _isTeleportEnabled ? 1u : 0u);
        } else if (context.reliableChannel) {
            LocalCacheEntry entry = _cache.localCache;
            if (entry.isTeleportEnabledSet) {
                _cache.PushLocalCacheToInflight(context.updateID);
                ClearCacheOnStreamCallback(context);
            }
            if (entry.isTeleportEnabledSet) {
                stream.WriteVarint32((uint)PropertyID.IsTeleportEnabled, entry.isTeleportEnabled ? 1u : 0u);
                didWriteProperties = true;
            }
            
            if (didWriteProperties) InvalidateReliableLength();
        }
    }
    
    protected override void Read(ReadStream stream, StreamContext context) {
        while (stream.ReadNextPropertyID(out uint propertyID)) {
            switch (propertyID) {
                case (uint)PropertyID.IsTeleportEnabled: {
                    bool previousValue = _isTeleportEnabled;
                    _isTeleportEnabled = (stream.ReadVarint32() != 0);
                    bool isTeleportEnabledExistsInChangeCache = _cache.ValueExistsInCache(entry => entry.isTeleportEnabledSet);
                    if (!isTeleportEnabledExistsInChangeCache && _isTeleportEnabled != previousValue) {
                        FireIsTeleportEnabledDidChange(_isTeleportEnabled);
                    }
                    break;
                }
                default: {
                    stream.SkipProperty();
                    break;
                }
            }
        }
    }
    
    #region Cache Operations
    
    private StreamEventDispatcher _streamEventDispatcher;
    
    private void FlattenCache() {
        _isTeleportEnabled = isTeleportEnabled;
        _cache.Clear();
    }
    
    private void ClearCache(uint updateID) {
        _cache.RemoveUpdateFromInflight(updateID);
    }
    
    private void ClearCacheOnStreamCallback(StreamContext context) {
        if (_streamEventDispatcher != context.dispatcher) {
            UnsubscribeClearCacheCallback(); // unsub from previous dispatcher
        }
        _streamEventDispatcher = context.dispatcher;
        _streamEventDispatcher.AddStreamCallback(context.updateID, ClearCache);
    }
    
    private void UnsubscribeClearCacheCallback() {
        if (_streamEventDispatcher != null) {
            _streamEventDispatcher.RemoveStreamCallback(ClearCache);
            _streamEventDispatcher = null;
        }
    }
    
    #endregion
}
/* ----- End Normal Autogenerated Code ----- */
