using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Normal.Realtime;
using Normal.Realtime.Serialization;

[RealtimeModel]
public partial class RealtimeNormcoreTourExit
{
    [RealtimeProperty(1, true, true)]
    private bool _isTourEnded;
}

/* ----- Begin Normal Autogenerated Code ----- */
public partial class RealtimeNormcoreTourExit : RealtimeModel {
    public bool isTourEnded {
        get {
            return _cache.LookForValueInCache(_isTourEnded, entry => entry.isTourEndedSet, entry => entry.isTourEnded);
        }
        set {
            if (this.isTourEnded == value) return;
            _cache.UpdateLocalCache(entry => { entry.isTourEndedSet = true; entry.isTourEnded = value; return entry; });
            InvalidateReliableLength();
            FireIsTourEndedDidChange(value);
        }
    }
    
    public delegate void PropertyChangedHandler<in T>(RealtimeNormcoreTourExit model, T value);
    public event PropertyChangedHandler<bool> isTourEndedDidChange;
    
    private struct LocalCacheEntry {
        public bool isTourEndedSet;
        public bool isTourEnded;
    }
    
    private LocalChangeCache<LocalCacheEntry> _cache = new LocalChangeCache<LocalCacheEntry>();
    
    public enum PropertyID : uint {
        IsTourEnded = 1,
    }
    
    public RealtimeNormcoreTourExit() : this(null) {
    }
    
    public RealtimeNormcoreTourExit(RealtimeModel parent) : base(null, parent) {
    }
    
    protected override void OnParentReplaced(RealtimeModel previousParent, RealtimeModel currentParent) {
        UnsubscribeClearCacheCallback();
    }
    
    private void FireIsTourEndedDidChange(bool value) {
        try {
            isTourEndedDidChange?.Invoke(this, value);
        } catch (System.Exception exception) {
            UnityEngine.Debug.LogException(exception);
        }
    }
    
    protected override int WriteLength(StreamContext context) {
        int length = 0;
        if (context.fullModel) {
            FlattenCache();
            length += WriteStream.WriteVarint32Length((uint)PropertyID.IsTourEnded, _isTourEnded ? 1u : 0u);
        } else if (context.reliableChannel) {
            LocalCacheEntry entry = _cache.localCache;
            if (entry.isTourEndedSet) {
                length += WriteStream.WriteVarint32Length((uint)PropertyID.IsTourEnded, entry.isTourEnded ? 1u : 0u);
            }
        }
        return length;
    }
    
    protected override void Write(WriteStream stream, StreamContext context) {
        var didWriteProperties = false;
        
        if (context.fullModel) {
            stream.WriteVarint32((uint)PropertyID.IsTourEnded, _isTourEnded ? 1u : 0u);
        } else if (context.reliableChannel) {
            LocalCacheEntry entry = _cache.localCache;
            if (entry.isTourEndedSet) {
                _cache.PushLocalCacheToInflight(context.updateID);
                ClearCacheOnStreamCallback(context);
            }
            if (entry.isTourEndedSet) {
                stream.WriteVarint32((uint)PropertyID.IsTourEnded, entry.isTourEnded ? 1u : 0u);
                didWriteProperties = true;
            }
            
            if (didWriteProperties) InvalidateReliableLength();
        }
    }
    
    protected override void Read(ReadStream stream, StreamContext context) {
        while (stream.ReadNextPropertyID(out uint propertyID)) {
            switch (propertyID) {
                case (uint)PropertyID.IsTourEnded: {
                    bool previousValue = _isTourEnded;
                    _isTourEnded = (stream.ReadVarint32() != 0);
                    bool isTourEndedExistsInChangeCache = _cache.ValueExistsInCache(entry => entry.isTourEndedSet);
                    if (!isTourEndedExistsInChangeCache && _isTourEnded != previousValue) {
                        FireIsTourEndedDidChange(_isTourEnded);
                    }
                    break;
                }
                default: {
                    stream.SkipProperty();
                    break;
                }
            }
        }
    }
    
    #region Cache Operations
    
    private StreamEventDispatcher _streamEventDispatcher;
    
    private void FlattenCache() {
        _isTourEnded = isTourEnded;
        _cache.Clear();
    }
    
    private void ClearCache(uint updateID) {
        _cache.RemoveUpdateFromInflight(updateID);
    }
    
    private void ClearCacheOnStreamCallback(StreamContext context) {
        if (_streamEventDispatcher != context.dispatcher) {
            UnsubscribeClearCacheCallback(); // unsub from previous dispatcher
        }
        _streamEventDispatcher = context.dispatcher;
        _streamEventDispatcher.AddStreamCallback(context.updateID, ClearCache);
    }
    
    private void UnsubscribeClearCacheCallback() {
        if (_streamEventDispatcher != null) {
            _streamEventDispatcher.RemoveStreamCallback(ClearCache);
            _streamEventDispatcher = null;
        }
    }
    
    #endregion
}
/* ----- End Normal Autogenerated Code ----- */
