using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Normal.Realtime;
using Normal.Realtime.Serialization;

[RealtimeModel]
public partial class UserIDModel
{
    [RealtimeProperty(1, true)]
    private int _userID;

    [RealtimeProperty(2, true)]
    private string _userIDCurrentScene;
}

/* ----- Begin Normal Autogenerated Code ----- */
public partial class UserIDModel : RealtimeModel {
    public int userID {
        get {
            return _cache.LookForValueInCache(_userID, entry => entry.userIDSet, entry => entry.userID);
        }
        set {
            if (this.userID == value) return;
            _cache.UpdateLocalCache(entry => { entry.userIDSet = true; entry.userID = value; return entry; });
            InvalidateReliableLength();
        }
    }
    
    public string userIDCurrentScene {
        get {
            return _cache.LookForValueInCache(_userIDCurrentScene, entry => entry.userIDCurrentSceneSet, entry => entry.userIDCurrentScene);
        }
        set {
            if (this.userIDCurrentScene == value) return;
            _cache.UpdateLocalCache(entry => { entry.userIDCurrentSceneSet = true; entry.userIDCurrentScene = value; return entry; });
            InvalidateReliableLength();
        }
    }
    
    private struct LocalCacheEntry {
        public bool userIDSet;
        public int userID;
        public bool userIDCurrentSceneSet;
        public string userIDCurrentScene;
    }
    
    private LocalChangeCache<LocalCacheEntry> _cache = new LocalChangeCache<LocalCacheEntry>();
    
    public enum PropertyID : uint {
        UserID = 1,
        UserIDCurrentScene = 2,
    }
    
    public UserIDModel() : this(null) {
    }
    
    public UserIDModel(RealtimeModel parent) : base(null, parent) {
    }
    
    protected override void OnParentReplaced(RealtimeModel previousParent, RealtimeModel currentParent) {
        UnsubscribeClearCacheCallback();
    }
    
    protected override int WriteLength(StreamContext context) {
        int length = 0;
        if (context.fullModel) {
            FlattenCache();
            length += WriteStream.WriteVarint32Length((uint)PropertyID.UserID, (uint)_userID);
            length += WriteStream.WriteStringLength((uint)PropertyID.UserIDCurrentScene, _userIDCurrentScene);
        } else if (context.reliableChannel) {
            LocalCacheEntry entry = _cache.localCache;
            if (entry.userIDSet) {
                length += WriteStream.WriteVarint32Length((uint)PropertyID.UserID, (uint)entry.userID);
            }
            if (entry.userIDCurrentSceneSet) {
                length += WriteStream.WriteStringLength((uint)PropertyID.UserIDCurrentScene, entry.userIDCurrentScene);
            }
        }
        return length;
    }
    
    protected override void Write(WriteStream stream, StreamContext context) {
        var didWriteProperties = false;
        
        if (context.fullModel) {
            stream.WriteVarint32((uint)PropertyID.UserID, (uint)_userID);
            stream.WriteString((uint)PropertyID.UserIDCurrentScene, _userIDCurrentScene);
        } else if (context.reliableChannel) {
            LocalCacheEntry entry = _cache.localCache;
            if (entry.userIDSet || entry.userIDCurrentSceneSet) {
                _cache.PushLocalCacheToInflight(context.updateID);
                ClearCacheOnStreamCallback(context);
            }
            if (entry.userIDSet) {
                stream.WriteVarint32((uint)PropertyID.UserID, (uint)entry.userID);
                didWriteProperties = true;
            }
            if (entry.userIDCurrentSceneSet) {
                stream.WriteString((uint)PropertyID.UserIDCurrentScene, entry.userIDCurrentScene);
                didWriteProperties = true;
            }
            
            if (didWriteProperties) InvalidateReliableLength();
        }
    }
    
    protected override void Read(ReadStream stream, StreamContext context) {
        while (stream.ReadNextPropertyID(out uint propertyID)) {
            switch (propertyID) {
                case (uint)PropertyID.UserID: {
                    _userID = (int)stream.ReadVarint32();
                    break;
                }
                case (uint)PropertyID.UserIDCurrentScene: {
                    _userIDCurrentScene = stream.ReadString();
                    break;
                }
                default: {
                    stream.SkipProperty();
                    break;
                }
            }
        }
    }
    
    #region Cache Operations
    
    private StreamEventDispatcher _streamEventDispatcher;
    
    private void FlattenCache() {
        _userID = userID;
        _userIDCurrentScene = userIDCurrentScene;
        _cache.Clear();
    }
    
    private void ClearCache(uint updateID) {
        _cache.RemoveUpdateFromInflight(updateID);
    }
    
    private void ClearCacheOnStreamCallback(StreamContext context) {
        if (_streamEventDispatcher != context.dispatcher) {
            UnsubscribeClearCacheCallback(); // unsub from previous dispatcher
        }
        _streamEventDispatcher = context.dispatcher;
        _streamEventDispatcher.AddStreamCallback(context.updateID, ClearCache);
    }
    
    private void UnsubscribeClearCacheCallback() {
        if (_streamEventDispatcher != null) {
            _streamEventDispatcher.RemoveStreamCallback(ClearCache);
            _streamEventDispatcher = null;
        }
    }
    
    #endregion
}
/* ----- End Normal Autogenerated Code ----- */
